### PR TITLE
added acct abstraction pip

### PR DESCRIPTION
**Pull request by wschwab**
# Description

Added a new PIP proposing [EIP-3074](https://eips.ethereum.org/EIPS/eip-3074)-style Account Abstraction on POS.

This PR also adds an `assets/` directory in the root directory of the PIP repo, allowing proposals to link to assets such as images. This reflects the architecture of the Ethereum [EIP repo](https://github.com/ethereum/EIPs).

As this proposal asks for the implementation of an extent proposal in the EIP repo, the PIP borrows heavily and copies entire sections from the original EIP. While the EIP (as all EIPs) is CC0, the authors have been contacted, though no response has been received as of yet.

## Type of change

- [ *]  New PIP
- [ *]  My edit follows the style guidelines

### CODE REVIEW

**Comment by wschwab** [comment]
fwiw, Micah and Sam have both already responded that they're ok with the usage of materials from 3074, still waiting on Ansgar and lightclient, though they might be relying on Sam since it's a group chat with the three of them

(as mentioned in the PIP, the EIP is CC0, so it wouldn't actually need permission, but I figure that it's at least the polite thing to do)

**Review by hrook1 — CHANGES_REQUESTED** [review]
- There is still some wording from the template in this doc
- There are also references to EIP where it should state PIP
- Please update references to contain only the link and author

**Comment by wschwab** [comment]
@hrook1 I've handled the first two, but am not sure what you mean by the third. Could you elaborate?

**Comment by hrook1** [comment]
@wschwab on the referencing it should use a more concise format, like as follows:

- https://github.com/maticnetwork/bor/tree/poleary/wip-eip-3074 (WIP), Paul O'Leary

**Comment by wschwab** [comment]
I've rewritten the Reference Implementation section to be more in line with the format @hrook1 recommended, while preserving the information as separate paragraphs on each bullet point. lmk if this works.

**Review by hrook1 — APPROVED** [review]

**Pull request merged**
